/**List of Puerto Rico Towns ordered alphabetically */
export const PUERTO_RICO_TOWNS: string[] = [
  "Adjuntas, PR",
  "Aguada, PR",
  "Aguadilla, PR",
  "Aguas Buenas, PR",
  "Aibonito, PR",
  "Añasco, PR",
  "Arecibo, PR",
  "Arroyo, PR",
  "Barceloneta, PR",
  "Barranquitas, PR",
  "Bayamón, PR",
  "Cabo Rojo, PR",
  "Caguas, PR",
  "Camuy, PR",
  "Canóvanas, PR",
  "Carolina, PR",
  "Cataño, PR",
  "Cayey, PR",
  "Ceiba, PR",
  "Ciales, PR",
  "Cidra, PR",
  "Coamo, PR",
  "Comerío, PR",
  "Corozal, PR",
  "Culebra, PR",
  "Dorado, PR",
  "Fajardo, PR",
  "Florida, PR",
  "Guayama, PR",
  "Guayanilla, PR",
  "Guaynabo, PR",
  "Gurabo, PR",
  "Guánica, PR",
  "Hatillo, PR",
  "Hormigueros, PR",
  "Humacao, PR",
  "Isabela, PR",
  "Jayuya, PR",
  "Juana Díaz, PR",
  "Juncos, PR",
  "Lajas, PR",
  "Lares, PR",
  "Las Marías, PR",
  "Las Piedras, PR",
  "Loiza, PR",
  "Luquillo, PR",
  "Manatí, PR",
  "Maricao, PR",
  "Maunabo, PR",
  "Mayagüez, PR",
  "Moca, PR",
  "Morovis, PR",
  "Naguabo, PR",
  "Naranjito, PR",
  "Orocovis, PR",
  "Patillas, PR",
  "Peñuelas, PR",
  "Ponce, PR",
  "Quebradillas, PR",
  "Rincón, PR",
  "Rio Grande, PR",
  "Sabana Grande, PR",
  "Salinas, PR",
  "San Germán, PR",
  "San Juan, PR",
  "San Lorenzo, PR",
  "San Sebastián, PR",
  "Santa Isabel, PR",
  "Toa Alta, PR",
  "Toa Baja, PR",
  "Trujillo Alto, PR",
  "Utuado, PR",
  "Vega Alta, PR",
  "Vega Baja, PR",
  "Vieques, PR",
  "Villalba, PR",
  "Yabucoa, PR",
  "Yauco, PR",
];
